### ISSUE TITLE
How can I introduce Kotlin Power-assert to Android Project's Unit Test?

### ISSUE THREAD

**Issue by MasayukiSuda** [bnorm/kotlin-power-assert#109] opened 2024-08-15 11:07 UTC
Is it not possible to put it in an Android Project? 
Even if I follow the sample, it won't work. 
Please tell me why it doesn't work and how I can make it work.
```
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)

    kotlin("plugin.power-assert") version "2.0.0"
}

@OptIn(ExperimentalKotlinGradlePluginApi::class)
powerAssert {
    functions = listOf(
        "kotlin.assert",
        "kotlin.require",
        "kotlin.test.assertTrue",
        "kotlin.test.assertEquals",
        "kotlin.test.assertNull",
    )
    includedSourceSets = listOf(
        "app",
        "androidTest",
        "androidTestDebug",
        "androidTestRelease",
        "debug",
        "test",
        "main",
        "testDebug",
        "testFixtures",
        "testFixturesDebug",
        "testFixturesRelease",
        "testRelease",
        )
}
```

**Comment by bnorm** [comment] 2024-08-16 12:44
Duplicate of [KT-70702](https://youtrack.jetbrains.com/issue/KT-70702/How-can-I-introduce-Kotlin-Power-assert-to-Android-Projects-Unit-Test).

**Closed as not planned by bnorm** 2024-08-16 12:44 UTC
